from rte.rte import Rte, Zero, One, Atom, function, CProduct, CStar, Plus
from engine.rte.properties.semantics import accept_predicate
from core.symbol import Symbol, Ranked_Symbol
from copy import deepcopy



class derivatives():
    """
    A class to compute derivatives of rational tree expressions.
    The derivatives of rational tree expressions (RTEs) are a fundamental concept in the theory of formal languages and automata. The derivative of an RTE with respect to a symbol is a new RTE that represents the set of trees that can be obtained by removing the leading symbol from the trees generated by the original RTE. This operation is crucial for various applications, such as parsing, language recognition, and simplification of RTEs. The `derivatives` class provides a method to compute the derivative of an RTE with respect to a given symbol, handling different types of RTEs including Zero, One, Atom, function, Plus, CProduct, and CStar. The implementation ensures that the resulting derivative accurately reflects the structure and language generated by the original RTE after consuming the specified symbol.
    Attributes:
    - None
    Methods:
    - __init__: Initializes the derivatives class. 
    - derive: Computes the derivative of a given rational tree expression (RTE) with respect to a specified symbol and returns a set of resulting RTEs that represent the derivative. The method handles different types of RTEs, including Zero, One, Atom, function, Plus, CProduct, and CStar, by applying the appropriate logic to compute the derivative based on the structure and components of the original RTE.
    """


    def __init__(self):
        pass

    def derive(self, r: Rte, sym: Symbol)->set[Rte]:
        response = set()
        if isinstance(r, (Zero, One, Atom)):
            return set()
        if isinstance(r, function):
            if sym == r.symbol:
                if not isinstance(sym, Ranked_Symbol):
                    comp = function(Symbol('ε'), r.args)
                else:
                    eps= Ranked_Symbol('ε', rank=r.symbol.rank)
                    _args = deepcopy(r.args)
                    comp = function(eps, _args)   
                return({comp})
            return set()
        
        if isinstance(r, Plus):
            for t in r.terms:
                response |= self.derive(t, sym)
            return response
        
        if isinstance(r, CStar):
            for d in self.derive(r.expr, sym):
                response.add(CProduct(d, r, r.concat))
            return response
        
        if isinstance(r, CProduct):
            if isinstance(sym, Ranked_Symbol):
                _concat=Ranked_Symbol(r.concat, rank=0)
            else:
                _concat =Symbol(r.concat)
            for d in self.derive(r.left, sym):
                response.add(CProduct(d, r.right, concat=_concat))
            if accept_predicate(r.left, r.concat):
                response |= (self.derive(r.right),sym)
            return(response)

#example usage

if __name__ == "__main__":
    a = Ranked_Symbol("a")
    b = Ranked_Symbol("b")
    f = Ranked_Symbol("f", rank=2)
    g = Ranked_Symbol("g", rank=1)

    # RTEs
    fab = CProduct(function(f, [function(a, []), function(b, [])]), function(f, [function(a, []), function(b, [])]), concat=a)
    gx = function(g, [function(a, [])])

    # rational tree expression
    rte0 = Plus(
        CStar(fab, concat=a),
        CProduct(fab, gx, concat=a),
        CStar(fab, concat=a)
    )
    #print(rte0)
    der = derivatives()
    #print(der.derive(rte0, f)) 
    #print(der.derive(rte0, g))           

# second example
    h = Ranked_Symbol("h", rank=1)
    E1 = function(f, [function(g,[function(h, [Atom(a)])]), function(g,[function(b, [])])])
    E1 = CStar(E1, a)
    #print(E1)
    E2= function(h, [function(a, [])]) 
    #print(E2)
    E3 = function(h,[function(b, [])])
    E2= Plus(E2,E3)
    #print(E2)
    rte1 = CProduct(E1, E2, b)
    print(rte1)
    print(der.derive(rte1, g))
              
